### ISSUE TITLE
pip package missing wetb and tools sub folders

### ISSUE THREAD

**Issue by mutricyl** [ebranlard/weio#27]
Hello

When using weio with pip package (`pip install weio`) some folders are missing that prevent weio to read files:

```
weio.read('data/HAN016_V105_Wd000_Wv000_H063_T105_C180_S01.out')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\laurent.mutricy\AppData\Local\miniconda3\envs\py310\lib\site-packages\weio\__init__.py", line 246, in read
    fileformat,F = detectFormat(filename, **kwargs)
  File "C:\Users\laurent.mutricy\AppData\Local\miniconda3\envs\py310\lib\site-packages\weio\__init__.py", line 212, in detectFormat
    formats=fileFormats()
  File "C:\Users\laurent.mutricy\AppData\Local\miniconda3\envs\py310\lib\site-packages\weio\__init__.py", line 32, in fileFormats
    from .hawc2_pc_file           import HAWC2PCFile
  File "C:\Users\laurent.mutricy\AppData\Local\miniconda3\envs\py310\lib\site-packages\weio\hawc2_pc_file.py", line 15, in <module>
    from .wetb.hawc2.pc_file import PCFile
ModuleNotFoundError: No module named 'weio.wetb'
```

May I suggest to modify setup.py line 39 from `packages=find_packages(include=['weio'],exclude=['./__init__.py']),`   to  `packages=find_packages(include=['weio', 'weio/wetb', 'weio/tools'],exclude=['./__init__.py']),` to solve the issue ?

**Comment by mutricyl** [comment]
looks like a duplicate of #22 

Sorry I have suggested an improper modification.
`find_packages(include=['weio', 'weio.wetb*', 'weio.tools'],exclude=['./__init__.py'])` should perform better.

**Comment by ebranlard** [comment]
Thank you for your help!

**Comment by cambrown52** [comment]
Hi @ebranlard,
I have started to use the weio toolbox and I have encountered this issue about missing dependency to wetb. It seems like this issue was fixed in the dev branch. Would it be possible to make a new release of the package to pypi with these fixes?
If there is anything I can do to make it happen, I'd be happy to help!

**Comment by ebranlard** [comment]
Hi Cam,

Can you try to see if `pip install weio`  now works for you? 
Please report any bug you see, I'm happy to fix them.
